### ISSUE TITLE
An English version of the doc page would be helpful

### ISSUE THREAD

**Issue by robinro** [osyo-manga/vim-hopping#1]
Thanks for the plugin. It looks really interesting. Could you please provide an English version of the help page?

**Comment by vysakh0** [comment]
@robinro @osyo-manga Any idea on how to switch between the results, tried arrow keys, also tried `C-n`, `C-p`, it does not seem to move to next or previous results, but in the gif it was shown ?

**Comment by osyo-manga** [comment]
> Thanks for the plugin. It looks really interesting. Could you please provide an English version of the help page?

Sorry, I can't English :(

> Any idea on how to switch between the results, tried arrow keys, also tried C-n, C-p, it does not seem to move to next or previous results, but in the gif it was shown ?

Please next setting.

``` vim
let g:hopping#keymapping = {
\   "\<C-n>" : "<Over>(hopping-next)",
\   "\<C-p>" : "<Over>(hopping-prev)",
\}
```

**Comment by vysakh0** [comment]
@osyo-manga Great! thank you! :smiley:
