### ISSUE TITLE
No such highlight group name: Cursor

### ISSUE THREAD

**Issue by xoliver** [osyo-manga/vim-hopping#2]
Hi there, thanks for this great plugin!

I'm encountering the same issue as described here:
https://github.com/haya14busa/vim-operator-flashy/issues/7
https://github.com/easymotion/vim-easymotion/issues/275

`No such highlight group name: Cursor`

Defining this on vimrc or during the session seems to fix it, if that helps:
`highlight default Cursor term=reverse cterm=reverse gui=reverse`

Thanks!

**Comment by osyo-manga** [comment]
Thanks!
I fixed it.

**Comment by xoliver** [comment]
It works - confirmed! Domo arigato for your time 😄
