### ISSUE TITLE
Folding problem

### ISSUE THREAD

**Issue by ipod825** [osyo-manga/vim-hopping#4]
Thanks for the great plugin! However, I have a problem that when using this with folding, the folds will not automatically open. It should be easy to solve this problem by adding `set nofoldenable` when calling HoppingStart. However, I don't know if it's possible to `set foldenable` when hopping ends so that the folds restore to the original status?

**Comment by ipod825** [comment]
nvm, I just send a pull request.

**Comment by osyo-manga** [comment]
Thanks for issues :)
I trying implementation.

**Comment by osyo-manga** [comment]
I implemented it. Please update plugin and check.

**Comment by ipod825** [comment]
It works. Thanks!!!

**Comment by osyo-manga** [comment]
OK, Thanks for issues and pull request :))

**Comment by ipod825** [comment]
Wait. It now raise another problem. When foldenable is set, when you press `<CR>` in hopping, you will remain at the same line when you call HoppingStart. I guees this is because you restore from mkview.

**Comment by osyo-manga** [comment]
Oops, Thanks!!
I fixed it, Please check!

**Comment by ipod825** [comment]
Works well now. Thanks.

**Comment by osyo-manga** [comment]
Thanks!!!
